### ISSUE TITLE
Need ability to set JVM parameters for GAE

### ISSUE THREAD

**Issue by msgilligan** [bmuschko/gradle-gae-plugin#14]
Specifically, I need to workaround this GAE bug:
http://code.google.com/p/googleappengine/issues/detail?id=6928

**Comment by bmuschko** [comment]
Added a new convention property named `jvmFlags` which takes in a list of JVM flags which should solve your problem. Check the [README file](https://github.com/bmuschko/gradle-gae-plugin/blob/master/README.md) for more information.

**Comment by msgilligan** [comment]
Thanks, now I'm just trying to figure out how to update my gaelyk gradlew configuration to use the new version of the plugin....

**Comment by bmuschko** [comment]
I actually had a look at this before but haven't checked it into the Gaelyk sources yet. In general you just need to update the defined version in your `build.gradle` file and run `./gradlew wrapper` so the latest version gets downloaded. There's at least one break change if you update to milestone 9:
- The dependency inclusion has to use `module` instead of `name`.
- The `buildscript` GitHub repository has to use dynamic properties.

**Comment by msgilligan** [comment]
Thanks, that should help.  We also might want to twist Guillaume's arm to make a new Gaelyk release...

**Comment by bmuschko** [comment]
I know that the other Gaelyk collaborator are currently working hard to optimize the build process. Guillaume even suggested that we'd release a new version soon. ;-) Feel free to chime in on the mailing list.

**Comment by msgilligan** [comment]
I'm planning on it, but I'm spread soo thin right now...

**Comment by msgilligan** [comment]
Haha, I"m pretty new to Gradle - what do I have to do to switch from name to module?

**Comment by bmuschko** [comment]
Looks like the [template project in master has been upgraded](https://github.com/glaforge/gaelyk/blob/master/template-project/build.gradle#L50) already to milestone 9 so you can check that out.
