### ISSUE TITLE
Using project root as the web-app directory

### ISSUE THREAD

**Issue by msgilligan** [bmuschko/gradle-gae-plugin#30]
Is this possible.  I would really like to do that for the iUI project (http://github.com/iui/iUI)  I am using Gaelyk and the gradle-gae-plugin but I really want to simplify the project directory structure.  Since most of the users and contributors are PHP coders, they have a hard time finding everything in the webapp directory.  (I've already simplified things by locating web-app only one level below the root, but would like to simplify it even more.)

Am I crazy?

p.s. Is there a mailing list for this project separate from the Gaelyk list?  Maybe I should ask the question there?

**Comment by truedat101** [comment]
Seems from the README: https://github.com/bmuschko/gradle-gae-plugin/blob/master/README.md that this question is addressed about how to set the default directory structure.  My observation under this configuration where we set an alternative directory (other than the gradle default) for war construction was that we get an error that srcDirs property was set to a path that did not exist.  I couldn't find a way to set this property for srcDirs so that it overwrote the default one.  Maybe I've overlooked a detail in how this should work when specifying alternate directories.

Gaelyk >= 1.2

Starting with version 1.2 Gaelyk adopted Gradle's default directory structure. The following changes are required to leverage Gaelyk's hot-reloading feature.

gae {
    warDir = file('src/main/webapp')
}

sourceSets.main.output.classesDir = 'src/main/webapp/WEB-INF/classes'

**Comment by bmuschko** [comment]
@msgilligan Did @truedat101 answer this question for you? It's correct that Gaelyk >= 1.2 adopted Gradle's default project layout. If you are using that version of Gaelyk you will need to stick to it. Prior to Gaelyk 1.2 you could use the project's root directory as value for the `warDir` parameter. Not sure if you saw that but I wrote about it in the [FAQ section](https://github.com/bmuschko/gradle-gae-plugin#faq). 

At the moment there's no separate mailing list for this project. So far people usually opened a ticket on GitHub or sent me a mail. That's fine with me.

**Comment by msgilligan** [comment]
So you're saying that I'm out of luck?  Is it impossible to fix this?  What if I use the gradle-gae-plugin without Gaelyk?  

And if I want to use '.' as warDir with Gaelyk maybe I should enter an issue for Gaelyk itself.

**Comment by truedat101** [comment]
@msgilligan  I guess we can submit a patch to this project if we come up with a plausible approach that fits in with the gradle conventions for configuration.  But question is whether it is so important to have a build system that can bootstrap itself or not, and how tied you are to groovy.  Normal use for packaging will be on a CI server, so any option, gradle, maven, ant, make, rake, grunt, ivy, etc. is likely to have some aspects you will want to have pre-installed in the host build system before you start.  I've already solved all of these problems to my satisfaction with Ant, Maven and SBT (Scala Build Tool) for other projects.  Let's discuss offline then what we will do for iUi.

**Comment by msgilligan** [comment]
@truedat101 We need to discuss our options elsewhere, but if we do stick with Gradle and a fix for this issue isn't too hard, I'd be interested in working on a patch.

**Comment by msgilligan** [comment]
I'd certainly be happy to QA a patch :)

**Comment by bmuschko** [comment]
The GAE plugin can adapt to any project structure that represents an exploded WAR directory. All you need to do is to set the value of the `warDir` convention property. Even though Gaelyk introduced Gradle's default project layout with version 1.2 you could still change it to your desired format. Keep in mind that you will need to change the project settings in your Gradle script as well. As you are diverging from the default conventions upgrading your Gaelyk version might be harder. You'd have to manually change your script instead of replacing it. In an upcoming version of Gaelyk a lot of the boilerplate code from the build script will be moved to Gaelyk plugin.

On the other hand is changing code in the `webapp` directory really so confusing to PHP developers? IMHO it's just a matter of documenting where code needs to be added or changed. Feel free to start a conversion about this on the Gaelyk mailing list.

**Comment by msgilligan** [comment]
@bmuschko We had to add a symbolic link from src/main/webapp to ../../web-app to get things to work in the current configuration:

https://github.com/iui/iUI/commit/45380c111dc83856c590ac1b6a77f1ba24f39673

I naively tried the same thing with a symbolic link from src/main/webapp to the project root and the cycle in the directory structure was causing an infinite loop during deploy that would have filled my hard drive.

@truedat101 and I would really like to see a fix for this.  Our project is a keep-it-simple JavaScript framework that is backend agnostic.  We want to make the JVM-based tooling we are using as invisible as possible to users that don't use it and as simple as possible to more advanced users (but without JVM backgrounds) who do use it.  We want to do a major reorganization and simplification of our directory structure in the new release we are about to start working on and this is an issue we need to resolve before starting on that.  It is important enough to us where we would consider switching away from GAE altogether to resolve it.

Are you familiar with the problem that is causing us to have to make the symbolic link?  Is that the only thing that is preventing us from setting warDir = file('.')?

**Comment by truedat101** [comment]
@msgilligan I naively tried to make this iUi packaging work as you had it, but kept getting the srcDirs error pointing to some path that DNE.  Sorting that problem out led me to the README for this plugin.  I think I might have missed some detail on how to set this property.  Without controlling that value, I could not work around the problem of the current directory structure layout without adding the softlink.  I will review how, through Gaelyk, to change the project layout convention, which is what we are attempting to do.

**Comment by bmuschko** [comment]
Please address this issue in the [new repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin) of the plugin.
